<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AssemblyName>UzTypist</AssemblyName>
    <RootNamespace>UzTypist</RootNamespace>
    <Product>UzTypist</Product>
    <Company>Abdurasilov</Company>
    <Authors>Abdurasilov</Authors>
    <Copyright>© 2026 Abdurasilov</Copyright>
    <Description>Oʻzbek lotin yozuvidagi maxsus belgilarni avtomatik toʻgʻrilaydigan Windows dasturi.</Description>
    <Version>1.0.0</Version>
    <ApplicationIcon>assets\uz-typist.ico</ApplicationIcon>

    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\uz-typist.ico">
      <LogicalName>UzTypist.uz-typist.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
